<?php
/** Auto-generated from sensor_Crop_Dataset.csv on 2025-08-20T09:46:30+02:00 */
$CROP_RULES = array (
  0 => 
  array (
    'name' => 'Maize – Dent',
    'Crop' => 'Maize',
    'Variety' => 'Dent',
    'Soil_Type' => 'Peaty',
    'N' => 83.31,
    'P' => 48.32,
    'K' => 54.43,
    'pH' => 6.57,
  ),
  1 => 
  array (
    'name' => 'Maize – Dent',
    'Crop' => 'Maize',
    'Variety' => 'Dent',
    'Soil_Type' => 'Silt',
    'N' => 90.65,
    'P' => 40.41,
    'K' => 58.73,
    'pH' => 6.13,
  ),
  2 => 
  array (
    'name' => 'Maize – Dent',
    'Crop' => 'Maize',
    'Variety' => 'Dent',
    'Soil_Type' => 'Sandy',
    'N' => 79.31,
    'P' => 49.76,
    'K' => 51.82,
    'pH' => 6.6,
  ),
  3 => 
  array (
    'name' => 'Maize – Dent',
    'Crop' => 'Maize',
    'Variety' => 'Dent',
    'Soil_Type' => 'Saline',
    'N' => 87.93,
    'P' => 50.26,
    'K' => 48.37,
    'pH' => 6.6,
  ),
  4 => 
  array (
    'name' => 'Maize – Dent',
    'Crop' => 'Maize',
    'Variety' => 'Dent',
    'Soil_Type' => 'Loamy',
    'N' => 75.32,
    'P' => 44.39,
    'K' => 62.53,
    'pH' => 6.68,
  ),
  5 => 
  array (
    'name' => 'Maize – Dent',
    'Crop' => 'Maize',
    'Variety' => 'Dent',
    'Soil_Type' => 'Clay',
    'N' => 88.17,
    'P' => 48.13,
    'K' => 58.01,
    'pH' => 6.44,
  ),
  6 => 
  array (
    'name' => 'Maize – Flint',
    'Crop' => 'Maize',
    'Variety' => 'Flint',
    'Soil_Type' => 'Saline',
    'N' => 73.15,
    'P' => 44.69,
    'K' => 60.04,
    'pH' => 6.33,
  ),
  7 => 
  array (
    'name' => 'Maize – Flint',
    'Crop' => 'Maize',
    'Variety' => 'Flint',
    'Soil_Type' => 'Peaty',
    'N' => 83.19,
    'P' => 50.64,
    'K' => 49.48,
    'pH' => 6.49,
  ),
  8 => 
  array (
    'name' => 'Maize – Flint',
    'Crop' => 'Maize',
    'Variety' => 'Flint',
    'Soil_Type' => 'Sandy',
    'N' => 77.2,
    'P' => 47.17,
    'K' => 52.24,
    'pH' => 6.49,
  ),
  9 => 
  array (
    'name' => 'Maize – Flint',
    'Crop' => 'Maize',
    'Variety' => 'Flint',
    'Soil_Type' => 'Loamy',
    'N' => 90.48,
    'P' => 44.45,
    'K' => 51.3,
    'pH' => 6.56,
  ),
  10 => 
  array (
    'name' => 'Maize – Flint',
    'Crop' => 'Maize',
    'Variety' => 'Flint',
    'Soil_Type' => 'Silt',
    'N' => 70.95,
    'P' => 48.11,
    'K' => 58.63,
    'pH' => 6.76,
  ),
  11 => 
  array (
    'name' => 'Maize – Flint',
    'Crop' => 'Maize',
    'Variety' => 'Flint',
    'Soil_Type' => 'Clay',
    'N' => 80.69,
    'P' => 47.44,
    'K' => 52.42,
    'pH' => 6.56,
  ),
  12 => 
  array (
    'name' => 'Maize – Sweet',
    'Crop' => 'Maize',
    'Variety' => 'Sweet',
    'Soil_Type' => 'Sandy',
    'N' => 81.91,
    'P' => 44.2,
    'K' => 54.11,
    'pH' => 6.62,
  ),
  13 => 
  array (
    'name' => 'Maize – Sweet',
    'Crop' => 'Maize',
    'Variety' => 'Sweet',
    'Soil_Type' => 'Clay',
    'N' => 77.19,
    'P' => 43.61,
    'K' => 54.81,
    'pH' => 6.47,
  ),
  14 => 
  array (
    'name' => 'Maize – Sweet',
    'Crop' => 'Maize',
    'Variety' => 'Sweet',
    'Soil_Type' => 'Peaty',
    'N' => 86.54,
    'P' => 45.43,
    'K' => 53.77,
    'pH' => 6.54,
  ),
  15 => 
  array (
    'name' => 'Maize – Sweet',
    'Crop' => 'Maize',
    'Variety' => 'Sweet',
    'Soil_Type' => 'Loamy',
    'N' => 74.09,
    'P' => 45.37,
    'K' => 54.42,
    'pH' => 6.5,
  ),
  16 => 
  array (
    'name' => 'Maize – Sweet',
    'Crop' => 'Maize',
    'Variety' => 'Sweet',
    'Soil_Type' => 'Saline',
    'N' => 75.03,
    'P' => 41.25,
    'K' => 56.38,
    'pH' => 6.44,
  ),
  17 => 
  array (
    'name' => 'Maize – Sweet',
    'Crop' => 'Maize',
    'Variety' => 'Sweet',
    'Soil_Type' => 'Silt',
    'N' => 75.14,
    'P' => 47.59,
    'K' => 52.11,
    'pH' => 6.44,
  ),
  18 => 
  array (
    'name' => 'Potato – Red',
    'Crop' => 'Potato',
    'Variety' => 'Red',
    'Soil_Type' => 'Sandy',
    'N' => 66.35,
    'P' => 50.25,
    'K' => 58.58,
    'pH' => 6.44,
  ),
  19 => 
  array (
    'name' => 'Potato – Red',
    'Crop' => 'Potato',
    'Variety' => 'Red',
    'Soil_Type' => 'Silt',
    'N' => 80.38,
    'P' => 45.87,
    'K' => 54.88,
    'pH' => 6.69,
  ),
  20 => 
  array (
    'name' => 'Potato – Red',
    'Crop' => 'Potato',
    'Variety' => 'Red',
    'Soil_Type' => 'Loamy',
    'N' => 74.3,
    'P' => 48.41,
    'K' => 59.27,
    'pH' => 6.39,
  ),
  21 => 
  array (
    'name' => 'Potato – Red',
    'Crop' => 'Potato',
    'Variety' => 'Red',
    'Soil_Type' => 'Clay',
    'N' => 66.68,
    'P' => 44.83,
    'K' => 53.26,
    'pH' => 6.51,
  ),
  22 => 
  array (
    'name' => 'Potato – Red',
    'Crop' => 'Potato',
    'Variety' => 'Red',
    'Soil_Type' => 'Peaty',
    'N' => 77.23,
    'P' => 49.99,
    'K' => 48.35,
    'pH' => 6.37,
  ),
  23 => 
  array (
    'name' => 'Potato – Red',
    'Crop' => 'Potato',
    'Variety' => 'Red',
    'Soil_Type' => 'Saline',
    'N' => 76.03,
    'P' => 44.53,
    'K' => 57.17,
    'pH' => 6.88,
  ),
  24 => 
  array (
    'name' => 'Potato – Russet',
    'Crop' => 'Potato',
    'Variety' => 'Russet',
    'Soil_Type' => 'Clay',
    'N' => 77.67,
    'P' => 47.97,
    'K' => 51.42,
    'pH' => 6.58,
  ),
  25 => 
  array (
    'name' => 'Potato – Russet',
    'Crop' => 'Potato',
    'Variety' => 'Russet',
    'Soil_Type' => 'Sandy',
    'N' => 79.52,
    'P' => 48.11,
    'K' => 61.32,
    'pH' => 6.37,
  ),
  26 => 
  array (
    'name' => 'Potato – Russet',
    'Crop' => 'Potato',
    'Variety' => 'Russet',
    'Soil_Type' => 'Silt',
    'N' => 82.84,
    'P' => 50.29,
    'K' => 50.52,
    'pH' => 6.32,
  ),
  27 => 
  array (
    'name' => 'Potato – Russet',
    'Crop' => 'Potato',
    'Variety' => 'Russet',
    'Soil_Type' => 'Peaty',
    'N' => 72.41,
    'P' => 50.1,
    'K' => 58.96,
    'pH' => 6.39,
  ),
  28 => 
  array (
    'name' => 'Potato – Russet',
    'Crop' => 'Potato',
    'Variety' => 'Russet',
    'Soil_Type' => 'Loamy',
    'N' => 70.57,
    'P' => 46.49,
    'K' => 55.99,
    'pH' => 6.43,
  ),
  29 => 
  array (
    'name' => 'Potato – Russet',
    'Crop' => 'Potato',
    'Variety' => 'Russet',
    'Soil_Type' => 'Saline',
    'N' => 73.58,
    'P' => 49.32,
    'K' => 55.29,
    'pH' => 6.61,
  ),
  30 => 
  array (
    'name' => 'Potato – Yukon Gold',
    'Crop' => 'Potato',
    'Variety' => 'Yukon Gold',
    'Soil_Type' => 'Saline',
    'N' => 81.87,
    'P' => 45.5,
    'K' => 58.32,
    'pH' => 6.59,
  ),
  31 => 
  array (
    'name' => 'Potato – Yukon Gold',
    'Crop' => 'Potato',
    'Variety' => 'Yukon Gold',
    'Soil_Type' => 'Loamy',
    'N' => 78.73,
    'P' => 47.1,
    'K' => 64.09,
    'pH' => 6.46,
  ),
  32 => 
  array (
    'name' => 'Potato – Yukon Gold',
    'Crop' => 'Potato',
    'Variety' => 'Yukon Gold',
    'Soil_Type' => 'Silt',
    'N' => 67.79,
    'P' => 48.68,
    'K' => 53.09,
    'pH' => 6.73,
  ),
  33 => 
  array (
    'name' => 'Potato – Yukon Gold',
    'Crop' => 'Potato',
    'Variety' => 'Yukon Gold',
    'Soil_Type' => 'Peaty',
    'N' => 69.09,
    'P' => 51.12,
    'K' => 47.86,
    'pH' => 6.16,
  ),
  34 => 
  array (
    'name' => 'Potato – Yukon Gold',
    'Crop' => 'Potato',
    'Variety' => 'Yukon Gold',
    'Soil_Type' => 'Clay',
    'N' => 78.2,
    'P' => 48.23,
    'K' => 44.87,
    'pH' => 6.77,
  ),
  35 => 
  array (
    'name' => 'Potato – Yukon Gold',
    'Crop' => 'Potato',
    'Variety' => 'Yukon Gold',
    'Soil_Type' => 'Sandy',
    'N' => 70.66,
    'P' => 45.89,
    'K' => 56.19,
    'pH' => 6.44,
  ),
  36 => 
  array (
    'name' => 'Rice – Arborio',
    'Crop' => 'Rice',
    'Variety' => 'Arborio',
    'Soil_Type' => 'Silt',
    'N' => 77.78,
    'P' => 49.26,
    'K' => 59.63,
    'pH' => 6.59,
  ),
  37 => 
  array (
    'name' => 'Rice – Arborio',
    'Crop' => 'Rice',
    'Variety' => 'Arborio',
    'Soil_Type' => 'Peaty',
    'N' => 84.31,
    'P' => 49.19,
    'K' => 57.59,
    'pH' => 6.33,
  ),
  38 => 
  array (
    'name' => 'Rice – Arborio',
    'Crop' => 'Rice',
    'Variety' => 'Arborio',
    'Soil_Type' => 'Sandy',
    'N' => 85.53,
    'P' => 52.76,
    'K' => 56.75,
    'pH' => 6.6,
  ),
  39 => 
  array (
    'name' => 'Rice – Arborio',
    'Crop' => 'Rice',
    'Variety' => 'Arborio',
    'Soil_Type' => 'Clay',
    'N' => 74.06,
    'P' => 45.18,
    'K' => 57.1,
    'pH' => 6.46,
  ),
  40 => 
  array (
    'name' => 'Rice – Arborio',
    'Crop' => 'Rice',
    'Variety' => 'Arborio',
    'Soil_Type' => 'Saline',
    'N' => 80.2,
    'P' => 47.24,
    'K' => 55.03,
    'pH' => 6.38,
  ),
  41 => 
  array (
    'name' => 'Rice – Arborio',
    'Crop' => 'Rice',
    'Variety' => 'Arborio',
    'Soil_Type' => 'Loamy',
    'N' => 58.75,
    'P' => 54.47,
    'K' => 60.9,
    'pH' => 6.63,
  ),
  42 => 
  array (
    'name' => 'Rice – Basmati',
    'Crop' => 'Rice',
    'Variety' => 'Basmati',
    'Soil_Type' => 'Silt',
    'N' => 75.74,
    'P' => 44.78,
    'K' => 53.86,
    'pH' => 6.61,
  ),
  43 => 
  array (
    'name' => 'Rice – Basmati',
    'Crop' => 'Rice',
    'Variety' => 'Basmati',
    'Soil_Type' => 'Sandy',
    'N' => 68.28,
    'P' => 49.2,
    'K' => 58.45,
    'pH' => 6.66,
  ),
  44 => 
  array (
    'name' => 'Rice – Basmati',
    'Crop' => 'Rice',
    'Variety' => 'Basmati',
    'Soil_Type' => 'Peaty',
    'N' => 83.63,
    'P' => 53.38,
    'K' => 52.65,
    'pH' => 6.58,
  ),
  45 => 
  array (
    'name' => 'Rice – Basmati',
    'Crop' => 'Rice',
    'Variety' => 'Basmati',
    'Soil_Type' => 'Clay',
    'N' => 81.73,
    'P' => 46.1,
    'K' => 53.07,
    'pH' => 6.58,
  ),
  46 => 
  array (
    'name' => 'Rice – Basmati',
    'Crop' => 'Rice',
    'Variety' => 'Basmati',
    'Soil_Type' => 'Loamy',
    'N' => 75.54,
    'P' => 45.58,
    'K' => 56.7,
    'pH' => 6.58,
  ),
  47 => 
  array (
    'name' => 'Rice – Basmati',
    'Crop' => 'Rice',
    'Variety' => 'Basmati',
    'Soil_Type' => 'Saline',
    'N' => 72.47,
    'P' => 44.96,
    'K' => 51.32,
    'pH' => 6.42,
  ),
  48 => 
  array (
    'name' => 'Rice – Jasmine',
    'Crop' => 'Rice',
    'Variety' => 'Jasmine',
    'Soil_Type' => 'Saline',
    'N' => 72.15,
    'P' => 49.01,
    'K' => 56.11,
    'pH' => 6.27,
  ),
  49 => 
  array (
    'name' => 'Rice – Jasmine',
    'Crop' => 'Rice',
    'Variety' => 'Jasmine',
    'Soil_Type' => 'Silt',
    'N' => 79.86,
    'P' => 51.05,
    'K' => 56.83,
    'pH' => 6.55,
  ),
  50 => 
  array (
    'name' => 'Rice – Jasmine',
    'Crop' => 'Rice',
    'Variety' => 'Jasmine',
    'Soil_Type' => 'Peaty',
    'N' => 69.17,
    'P' => 47.42,
    'K' => 46.81,
    'pH' => 6.47,
  ),
  51 => 
  array (
    'name' => 'Rice – Jasmine',
    'Crop' => 'Rice',
    'Variety' => 'Jasmine',
    'Soil_Type' => 'Sandy',
    'N' => 74.83,
    'P' => 46.51,
    'K' => 53.13,
    'pH' => 6.53,
  ),
  52 => 
  array (
    'name' => 'Rice – Jasmine',
    'Crop' => 'Rice',
    'Variety' => 'Jasmine',
    'Soil_Type' => 'Loamy',
    'N' => 76.47,
    'P' => 43.85,
    'K' => 50.08,
    'pH' => 6.43,
  ),
  53 => 
  array (
    'name' => 'Rice – Jasmine',
    'Crop' => 'Rice',
    'Variety' => 'Jasmine',
    'Soil_Type' => 'Clay',
    'N' => 72.96,
    'P' => 47.45,
    'K' => 64.82,
    'pH' => 6.53,
  ),
  54 => 
  array (
    'name' => 'Sugarcane – Co 0238',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 0238',
    'Soil_Type' => 'Silt',
    'N' => 83.04,
    'P' => 46.48,
    'K' => 53.31,
    'pH' => 6.14,
  ),
  55 => 
  array (
    'name' => 'Sugarcane – Co 0238',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 0238',
    'Soil_Type' => 'Saline',
    'N' => 75.35,
    'P' => 47.55,
    'K' => 56.05,
    'pH' => 6.29,
  ),
  56 => 
  array (
    'name' => 'Sugarcane – Co 0238',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 0238',
    'Soil_Type' => 'Loamy',
    'N' => 74.34,
    'P' => 50.2,
    'K' => 55.84,
    'pH' => 6.52,
  ),
  57 => 
  array (
    'name' => 'Sugarcane – Co 0238',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 0238',
    'Soil_Type' => 'Peaty',
    'N' => 75.52,
    'P' => 45.72,
    'K' => 60.1,
    'pH' => 6.52,
  ),
  58 => 
  array (
    'name' => 'Sugarcane – Co 0238',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 0238',
    'Soil_Type' => 'Sandy',
    'N' => 75.97,
    'P' => 45.51,
    'K' => 58.01,
    'pH' => 6.67,
  ),
  59 => 
  array (
    'name' => 'Sugarcane – Co 0238',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 0238',
    'Soil_Type' => 'Clay',
    'N' => 79.35,
    'P' => 44.24,
    'K' => 62.76,
    'pH' => 6.69,
  ),
  60 => 
  array (
    'name' => 'Sugarcane – Co 86032',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 86032',
    'Soil_Type' => 'Clay',
    'N' => 79.19,
    'P' => 43.78,
    'K' => 58.5,
    'pH' => 6.59,
  ),
  61 => 
  array (
    'name' => 'Sugarcane – Co 86032',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 86032',
    'Soil_Type' => 'Peaty',
    'N' => 87.05,
    'P' => 50.22,
    'K' => 54.44,
    'pH' => 6.23,
  ),
  62 => 
  array (
    'name' => 'Sugarcane – Co 86032',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 86032',
    'Soil_Type' => 'Sandy',
    'N' => 66.57,
    'P' => 43.71,
    'K' => 53.4,
    'pH' => 6.49,
  ),
  63 => 
  array (
    'name' => 'Sugarcane – Co 86032',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 86032',
    'Soil_Type' => 'Saline',
    'N' => 80.8,
    'P' => 47.82,
    'K' => 55.16,
    'pH' => 6.34,
  ),
  64 => 
  array (
    'name' => 'Sugarcane – Co 86032',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 86032',
    'Soil_Type' => 'Silt',
    'N' => 85.06,
    'P' => 41.91,
    'K' => 58.3,
    'pH' => 6.6,
  ),
  65 => 
  array (
    'name' => 'Sugarcane – Co 86032',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 86032',
    'Soil_Type' => 'Loamy',
    'N' => 75.4,
    'P' => 38.74,
    'K' => 53.59,
    'pH' => 6.72,
  ),
  66 => 
  array (
    'name' => 'Sugarcane – Co 99004',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 99004',
    'Soil_Type' => 'Loamy',
    'N' => 78.4,
    'P' => 47.94,
    'K' => 51.2,
    'pH' => 6.29,
  ),
  67 => 
  array (
    'name' => 'Sugarcane – Co 99004',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 99004',
    'Soil_Type' => 'Clay',
    'N' => 72.95,
    'P' => 48.45,
    'K' => 58.61,
    'pH' => 6.62,
  ),
  68 => 
  array (
    'name' => 'Sugarcane – Co 99004',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 99004',
    'Soil_Type' => 'Saline',
    'N' => 86.02,
    'P' => 45.06,
    'K' => 54.85,
    'pH' => 6.67,
  ),
  69 => 
  array (
    'name' => 'Sugarcane – Co 99004',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 99004',
    'Soil_Type' => 'Sandy',
    'N' => 77.41,
    'P' => 49.1,
    'K' => 57.32,
    'pH' => 6.51,
  ),
  70 => 
  array (
    'name' => 'Sugarcane – Co 99004',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 99004',
    'Soil_Type' => 'Silt',
    'N' => 77.69,
    'P' => 44.47,
    'K' => 57.01,
    'pH' => 6.47,
  ),
  71 => 
  array (
    'name' => 'Sugarcane – Co 99004',
    'Crop' => 'Sugarcane',
    'Variety' => 'Co 99004',
    'Soil_Type' => 'Peaty',
    'N' => 78.71,
    'P' => 53.92,
    'K' => 57.96,
    'pH' => 6.85,
  ),
  72 => 
  array (
    'name' => 'Tomato – Beefsteak',
    'Crop' => 'Tomato',
    'Variety' => 'Beefsteak',
    'Soil_Type' => 'Clay',
    'N' => 80.44,
    'P' => 44.85,
    'K' => 56.04,
    'pH' => 6.35,
  ),
  73 => 
  array (
    'name' => 'Tomato – Beefsteak',
    'Crop' => 'Tomato',
    'Variety' => 'Beefsteak',
    'Soil_Type' => 'Loamy',
    'N' => 85.81,
    'P' => 47.96,
    'K' => 51.19,
    'pH' => 6.51,
  ),
  74 => 
  array (
    'name' => 'Tomato – Beefsteak',
    'Crop' => 'Tomato',
    'Variety' => 'Beefsteak',
    'Soil_Type' => 'Peaty',
    'N' => 76.06,
    'P' => 48.74,
    'K' => 55.75,
    'pH' => 6.46,
  ),
  75 => 
  array (
    'name' => 'Tomato – Beefsteak',
    'Crop' => 'Tomato',
    'Variety' => 'Beefsteak',
    'Soil_Type' => 'Silt',
    'N' => 71.37,
    'P' => 49.04,
    'K' => 51.72,
    'pH' => 6.53,
  ),
  76 => 
  array (
    'name' => 'Tomato – Beefsteak',
    'Crop' => 'Tomato',
    'Variety' => 'Beefsteak',
    'Soil_Type' => 'Saline',
    'N' => 84.92,
    'P' => 46.45,
    'K' => 56.37,
    'pH' => 6.48,
  ),
  77 => 
  array (
    'name' => 'Tomato – Beefsteak',
    'Crop' => 'Tomato',
    'Variety' => 'Beefsteak',
    'Soil_Type' => 'Sandy',
    'N' => 74.86,
    'P' => 48.94,
    'K' => 54.02,
    'pH' => 6.72,
  ),
  78 => 
  array (
    'name' => 'Tomato – Cherry',
    'Crop' => 'Tomato',
    'Variety' => 'Cherry',
    'Soil_Type' => 'Silt',
    'N' => 79.89,
    'P' => 43.64,
    'K' => 56.42,
    'pH' => 6.4,
  ),
  79 => 
  array (
    'name' => 'Tomato – Cherry',
    'Crop' => 'Tomato',
    'Variety' => 'Cherry',
    'Soil_Type' => 'Saline',
    'N' => 82.47,
    'P' => 43.79,
    'K' => 54.89,
    'pH' => 6.67,
  ),
  80 => 
  array (
    'name' => 'Tomato – Cherry',
    'Crop' => 'Tomato',
    'Variety' => 'Cherry',
    'Soil_Type' => 'Sandy',
    'N' => 79.21,
    'P' => 44.82,
    'K' => 53.62,
    'pH' => 6.36,
  ),
  81 => 
  array (
    'name' => 'Tomato – Cherry',
    'Crop' => 'Tomato',
    'Variety' => 'Cherry',
    'Soil_Type' => 'Peaty',
    'N' => 75.81,
    'P' => 45.88,
    'K' => 55.85,
    'pH' => 6.62,
  ),
  82 => 
  array (
    'name' => 'Tomato – Cherry',
    'Crop' => 'Tomato',
    'Variety' => 'Cherry',
    'Soil_Type' => 'Loamy',
    'N' => 75.79,
    'P' => 45.78,
    'K' => 57.34,
    'pH' => 6.25,
  ),
  83 => 
  array (
    'name' => 'Tomato – Cherry',
    'Crop' => 'Tomato',
    'Variety' => 'Cherry',
    'Soil_Type' => 'Clay',
    'N' => 67.84,
    'P' => 54.28,
    'K' => 56.2,
    'pH' => 6.45,
  ),
  84 => 
  array (
    'name' => 'Tomato – Roma',
    'Crop' => 'Tomato',
    'Variety' => 'Roma',
    'Soil_Type' => 'Clay',
    'N' => 67.08,
    'P' => 48.21,
    'K' => 52.62,
    'pH' => 6.3,
  ),
  85 => 
  array (
    'name' => 'Tomato – Roma',
    'Crop' => 'Tomato',
    'Variety' => 'Roma',
    'Soil_Type' => 'Sandy',
    'N' => 79.9,
    'P' => 48.1,
    'K' => 57.99,
    'pH' => 6.41,
  ),
  86 => 
  array (
    'name' => 'Tomato – Roma',
    'Crop' => 'Tomato',
    'Variety' => 'Roma',
    'Soil_Type' => 'Silt',
    'N' => 73.3,
    'P' => 41.49,
    'K' => 56.03,
    'pH' => 6.57,
  ),
  87 => 
  array (
    'name' => 'Tomato – Roma',
    'Crop' => 'Tomato',
    'Variety' => 'Roma',
    'Soil_Type' => 'Loamy',
    'N' => 77.85,
    'P' => 50.27,
    'K' => 47.42,
    'pH' => 6.44,
  ),
  88 => 
  array (
    'name' => 'Tomato – Roma',
    'Crop' => 'Tomato',
    'Variety' => 'Roma',
    'Soil_Type' => 'Peaty',
    'N' => 77.35,
    'P' => 46.62,
    'K' => 59.99,
    'pH' => 6.47,
  ),
  89 => 
  array (
    'name' => 'Tomato – Roma',
    'Crop' => 'Tomato',
    'Variety' => 'Roma',
    'Soil_Type' => 'Saline',
    'N' => 71.18,
    'P' => 47.16,
    'K' => 54.9,
    'pH' => 6.57,
  ),
  90 => 
  array (
    'name' => 'Wheat – Durum',
    'Crop' => 'Wheat',
    'Variety' => 'Durum',
    'Soil_Type' => 'Sandy',
    'N' => 74.47,
    'P' => 49.94,
    'K' => 55.15,
    'pH' => 6.48,
  ),
  91 => 
  array (
    'name' => 'Wheat – Durum',
    'Crop' => 'Wheat',
    'Variety' => 'Durum',
    'Soil_Type' => 'Silt',
    'N' => 66.98,
    'P' => 52.93,
    'K' => 56.8,
    'pH' => 6.4,
  ),
  92 => 
  array (
    'name' => 'Wheat – Durum',
    'Crop' => 'Wheat',
    'Variety' => 'Durum',
    'Soil_Type' => 'Peaty',
    'N' => 89.68,
    'P' => 44.11,
    'K' => 57.4,
    'pH' => 6.41,
  ),
  93 => 
  array (
    'name' => 'Wheat – Durum',
    'Crop' => 'Wheat',
    'Variety' => 'Durum',
    'Soil_Type' => 'Saline',
    'N' => 81.85,
    'P' => 52.62,
    'K' => 55.54,
    'pH' => 6.72,
  ),
  94 => 
  array (
    'name' => 'Wheat – Durum',
    'Crop' => 'Wheat',
    'Variety' => 'Durum',
    'Soil_Type' => 'Clay',
    'N' => 86.3,
    'P' => 48.96,
    'K' => 55.9,
    'pH' => 6.68,
  ),
  95 => 
  array (
    'name' => 'Wheat – Durum',
    'Crop' => 'Wheat',
    'Variety' => 'Durum',
    'Soil_Type' => 'Loamy',
    'N' => 79.51,
    'P' => 47.07,
    'K' => 57.04,
    'pH' => 6.24,
  ),
  96 => 
  array (
    'name' => 'Wheat – Hard Red',
    'Crop' => 'Wheat',
    'Variety' => 'Hard Red',
    'Soil_Type' => 'Sandy',
    'N' => 83.78,
    'P' => 48.68,
    'K' => 51.44,
    'pH' => 6.26,
  ),
  97 => 
  array (
    'name' => 'Wheat – Hard Red',
    'Crop' => 'Wheat',
    'Variety' => 'Hard Red',
    'Soil_Type' => 'Peaty',
    'N' => 79.95,
    'P' => 48.65,
    'K' => 57.4,
    'pH' => 6.36,
  ),
  98 => 
  array (
    'name' => 'Wheat – Hard Red',
    'Crop' => 'Wheat',
    'Variety' => 'Hard Red',
    'Soil_Type' => 'Loamy',
    'N' => 79.39,
    'P' => 46.9,
    'K' => 57.0,
    'pH' => 6.31,
  ),
  99 => 
  array (
    'name' => 'Wheat – Hard Red',
    'Crop' => 'Wheat',
    'Variety' => 'Hard Red',
    'Soil_Type' => 'Clay',
    'N' => 78.16,
    'P' => 50.18,
    'K' => 54.47,
    'pH' => 6.2,
  ),
  100 => 
  array (
    'name' => 'Wheat – Hard Red',
    'Crop' => 'Wheat',
    'Variety' => 'Hard Red',
    'Soil_Type' => 'Silt',
    'N' => 84.64,
    'P' => 51.76,
    'K' => 56.84,
    'pH' => 6.4,
  ),
  101 => 
  array (
    'name' => 'Wheat – Hard Red',
    'Crop' => 'Wheat',
    'Variety' => 'Hard Red',
    'Soil_Type' => 'Saline',
    'N' => 78.35,
    'P' => 54.33,
    'K' => 51.93,
    'pH' => 6.47,
  ),
  102 => 
  array (
    'name' => 'Wheat – Soft Red',
    'Crop' => 'Wheat',
    'Variety' => 'Soft Red',
    'Soil_Type' => 'Clay',
    'N' => 76.8,
    'P' => 54.12,
    'K' => 59.67,
    'pH' => 6.39,
  ),
  103 => 
  array (
    'name' => 'Wheat – Soft Red',
    'Crop' => 'Wheat',
    'Variety' => 'Soft Red',
    'Soil_Type' => 'Loamy',
    'N' => 83.67,
    'P' => 49.17,
    'K' => 56.84,
    'pH' => 6.61,
  ),
  104 => 
  array (
    'name' => 'Wheat – Soft Red',
    'Crop' => 'Wheat',
    'Variety' => 'Soft Red',
    'Soil_Type' => 'Saline',
    'N' => 76.73,
    'P' => 49.36,
    'K' => 50.19,
    'pH' => 6.51,
  ),
  105 => 
  array (
    'name' => 'Wheat – Soft Red',
    'Crop' => 'Wheat',
    'Variety' => 'Soft Red',
    'Soil_Type' => 'Sandy',
    'N' => 77.83,
    'P' => 48.19,
    'K' => 52.59,
    'pH' => 6.63,
  ),
  106 => 
  array (
    'name' => 'Wheat – Soft Red',
    'Crop' => 'Wheat',
    'Variety' => 'Soft Red',
    'Soil_Type' => 'Silt',
    'N' => 73.47,
    'P' => 52.89,
    'K' => 51.79,
    'pH' => 6.72,
  ),
  107 => 
  array (
    'name' => 'Wheat – Soft Red',
    'Crop' => 'Wheat',
    'Variety' => 'Soft Red',
    'Soil_Type' => 'Peaty',
    'N' => 87.48,
    'P' => 49.26,
    'K' => 56.92,
    'pH' => 6.38,
  ),
);
